-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9898yErOr7B99Agp
oaFyS9EaKKNrZsM2qDafVFD7WvWgCgYIKoZIzj0DAQehRANCAATMnxpppqRQoKuk
+rxOQFpBOgx7RqFZfH5mKAWlxQNzjAyUvwUsfVR0aS15hWkTDcShdCsh6GqfPRbd
oRLSS63x
-----END PRIVATE KEY-----